# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'test.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QLabel, QListView,
    QMainWindow, QProgressBar, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QTextBrowser, QWidget)

class Ui_Imageur3D(object):
    def setupUi(self, Imageur3D):
        if not Imageur3D.objectName():
            Imageur3D.setObjectName(u"Imageur3D")
        Imageur3D.resize(1080, 720)
        Imageur3D.setMinimumSize(QSize(1080, 720))
        Imageur3D.setMaximumSize(QSize(1080, 720))
        self.centralwidget = QWidget(Imageur3D)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1081, 661))
        self.scanTab = QWidget()
        self.scanTab.setObjectName(u"scanTab")
        self.checkBox_5 = QCheckBox(self.scanTab)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(600, 410, 121, 20))
        self.frangesButton_3 = QPushButton(self.scanTab)
        self.frangesButton_3.setObjectName(u"frangesButton_3")
        self.frangesButton_3.setGeometry(QRect(530, 430, 201, 31))
        self.autoScrollButton_3 = QCheckBox(self.scanTab)
        self.autoScrollButton_3.setObjectName(u"autoScrollButton_3")
        self.autoScrollButton_3.setGeometry(QRect(150, 490, 151, 31))
        self.autoScrollButton_3.setChecked(True)
        self.label_7 = QLabel(self.scanTab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(420, 480, 191, 41))
        self.label_7.setStyleSheet(u"font: 22pt \"MS Shell Dlg 2\";")
        self.progressBar_4 = QProgressBar(self.scanTab)
        self.progressBar_4.setObjectName(u"progressBar_4")
        self.progressBar_4.setGeometry(QRect(560, 490, 301, 23))
        self.progressBar_4.setValue(0)
        self.consoleLayout_2 = QTextBrowser(self.scanTab)
        self.consoleLayout_2.setObjectName(u"consoleLayout_2")
        self.consoleLayout_2.setGeometry(QRect(10, 530, 1051, 131))
        self.TroisDButton_3 = QPushButton(self.scanTab)
        self.TroisDButton_3.setObjectName(u"TroisDButton_3")
        self.TroisDButton_3.setGeometry(QRect(730, 410, 141, 51))
        self.label_8 = QLabel(self.scanTab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(710, 40, 271, 20))
        self.checkBox_6 = QCheckBox(self.scanTab)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(530, 410, 51, 20))
        self.simulateObjectButton_3 = QPushButton(self.scanTab)
        self.simulateObjectButton_3.setObjectName(u"simulateObjectButton_3")
        self.simulateObjectButton_3.setGeometry(QRect(390, 410, 141, 51))
        self.resultTabWidget_3 = QTabWidget(self.scanTab)
        self.resultTabWidget_3.setObjectName(u"resultTabWidget_3")
        self.resultTabWidget_3.setGeometry(QRect(30, 40, 621, 351))
        self.result_3 = QWidget()
        self.result_3.setObjectName(u"result_3")
        self.result_3.setStyleSheet(u"background-color : rgb(197,197,197);")
        self.affichage_3 = QLabel(self.result_3)
        self.affichage_3.setObjectName(u"affichage_3")
        self.affichage_3.setGeometry(QRect(0, 0, 621, 321))
        self.affichage_3.setStyleSheet(u"background-color: rgb(197,197,197);")
        self.resultTabWidget_3.addTab(self.result_3, "")
        self.autoButton_3 = QPushButton(self.scanTab)
        self.autoButton_3.setObjectName(u"autoButton_3")
        self.autoButton_3.setGeometry(QRect(870, 410, 121, 51))
        self.informationList_3 = QListView(self.scanTab)
        self.informationList_3.setObjectName(u"informationList_3")
        self.informationList_3.setGeometry(QRect(700, 70, 291, 321))
        self.label_9 = QLabel(self.scanTab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 490, 111, 31))
        self.label_9.setStyleSheet(u"font: 22pt \"MS Shell Dlg 2\";")
        self.textBrowser = QTextBrowser(self.scanTab)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(330, 410, 16, 51))
        self.textBrowser.setStyleSheet(u"background-color : rgb(197,197,197);")
        self.calibEmetteurButton = QPushButton(self.scanTab)
        self.calibEmetteurButton.setObjectName(u"calibEmetteurButton")
        self.calibEmetteurButton.setGeometry(QRect(30, 440, 113, 41))
        self.calibReceptButton = QPushButton(self.scanTab)
        self.calibReceptButton.setObjectName(u"calibReceptButton")
        self.calibReceptButton.setGeometry(QRect(140, 440, 113, 41))
        self.mire_emet_check = QCheckBox(self.scanTab)
        self.mire_emet_check.setObjectName(u"mire_emet_check")
        self.mire_emet_check.setGeometry(QRect(30, 410, 101, 20))
        self.mire_recep_check = QCheckBox(self.scanTab)
        self.mire_recep_check.setObjectName(u"mire_recep_check")
        self.mire_recep_check.setGeometry(QRect(140, 410, 121, 20))
        self.tabWidget.addTab(self.scanTab, "")
        self.simulationTab = QWidget()
        self.simulationTab.setObjectName(u"simulationTab")
        self.label = QLabel(self.simulationTab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 480, 111, 31))
        self.label.setStyleSheet(u"font: 22pt \"MS Shell Dlg 2\";")
        self.simulateObjectButton = QPushButton(self.simulationTab)
        self.simulateObjectButton.setObjectName(u"simulateObjectButton")
        self.simulateObjectButton.setGeometry(QRect(30, 410, 141, 51))
        self.progressBar_2 = QProgressBar(self.simulationTab)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(560, 480, 301, 23))
        self.progressBar_2.setValue(0)
        self.label_3 = QLabel(self.simulationTab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(420, 470, 191, 41))
        self.label_3.setStyleSheet(u"font: 22pt \"MS Shell Dlg 2\";")
        self.resultTabWidget = QTabWidget(self.simulationTab)
        self.resultTabWidget.setObjectName(u"resultTabWidget")
        self.resultTabWidget.setGeometry(QRect(30, 30, 621, 351))
        self.result = QWidget()
        self.result.setObjectName(u"result")
        self.result.setStyleSheet(u"background-color : rgb(197,197,197);")
        self.affichage = QLabel(self.result)
        self.affichage.setObjectName(u"affichage")
        self.affichage.setGeometry(QRect(0, 0, 621, 321))
        self.affichage.setStyleSheet(u"background-color: rgb(197,197,197);")
        self.resultTabWidget.addTab(self.result, "")
        self.autoScrollButton = QCheckBox(self.simulationTab)
        self.autoScrollButton.setObjectName(u"autoScrollButton")
        self.autoScrollButton.setGeometry(QRect(150, 480, 151, 31))
        self.autoScrollButton.setChecked(True)
        self.informationList = QListView(self.simulationTab)
        self.informationList.setObjectName(u"informationList")
        self.informationList.setGeometry(QRect(700, 60, 291, 321))
        self.label_2 = QLabel(self.simulationTab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(710, 30, 271, 20))
        self.frangesButton = QPushButton(self.simulationTab)
        self.frangesButton.setObjectName(u"frangesButton")
        self.frangesButton.setGeometry(QRect(170, 430, 201, 31))
        self.TroisDButton = QPushButton(self.simulationTab)
        self.TroisDButton.setObjectName(u"TroisDButton")
        self.TroisDButton.setGeometry(QRect(370, 410, 141, 51))
        self.checkBox = QCheckBox(self.simulationTab)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(170, 410, 51, 20))
        self.checkBox_2 = QCheckBox(self.simulationTab)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(240, 410, 121, 20))
        self.autoButton = QPushButton(self.simulationTab)
        self.autoButton.setObjectName(u"autoButton")
        self.autoButton.setGeometry(QRect(520, 410, 121, 51))
        self.tabWidget.addTab(self.simulationTab, "")
        self.consoleLayout = QTextBrowser(self.centralwidget)
        self.consoleLayout.setObjectName(u"consoleLayout")
        self.consoleLayout.setGeometry(QRect(10, 560, 1051, 131))
        Imageur3D.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Imageur3D)
        self.statusbar.setObjectName(u"statusbar")
        Imageur3D.setStatusBar(self.statusbar)

        self.retranslateUi(Imageur3D)

        self.tabWidget.setCurrentIndex(0)
        self.resultTabWidget_3.setCurrentIndex(0)
        self.resultTabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Imageur3D)
    # setupUi

    def retranslateUi(self, Imageur3D):
        Imageur3D.setWindowTitle(QCoreApplication.translate("Imageur3D", u"Imageur 3D", None))
        self.checkBox_5.setText(QCoreApplication.translate("Imageur3D", u"Halo de lumi\u00e8re", None))
        self.frangesButton_3.setText(QCoreApplication.translate("Imageur3D", u"G\u00e9n\u00e9rer les franges", None))
        self.autoScrollButton_3.setText(QCoreApplication.translate("Imageur3D", u"AUTO SCROLL", None))
        self.label_7.setText(QCoreApplication.translate("Imageur3D", u"Progress :", None))
        self.TroisDButton_3.setText(QCoreApplication.translate("Imageur3D", u"Retrouver les \n"
" coordonn\u00e9es 3D", None))
        self.label_8.setText(QCoreApplication.translate("Imageur3D", u"<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Informations</span></p></body></html>", None))
        self.checkBox_6.setText(QCoreApplication.translate("Imageur3D", u"Bruit", None))
        self.simulateObjectButton_3.setText(QCoreApplication.translate("Imageur3D", u"Simuler un objet", None))
        self.affichage_3.setText(QCoreApplication.translate("Imageur3D", u"<html><head/><body><p align=\"center\">Ici s'affichera le r\u00e9sultat des diff\u00e9rentes \u00e9tapes du scan</p></body></html>", None))
        self.resultTabWidget_3.setTabText(self.resultTabWidget_3.indexOf(self.result_3), QCoreApplication.translate("Imageur3D", u"Resultat du scan", None))
        self.autoButton_3.setText(QCoreApplication.translate("Imageur3D", u"Auto", None))
        self.label_9.setText(QCoreApplication.translate("Imageur3D", u"Console :", None))
        self.calibEmetteurButton.setText(QCoreApplication.translate("Imageur3D", u"Calibrer \n"
" l'\u00e9metteur", None))
        self.calibReceptButton.setText(QCoreApplication.translate("Imageur3D", u"Calibrer le \n"
" r\u00e9cepteur", None))
        self.mire_emet_check.setText(QCoreApplication.translate("Imageur3D", u"Mire emetteur", None))
        self.mire_recep_check.setText(QCoreApplication.translate("Imageur3D", u"Mire recepteur", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scanTab), QCoreApplication.translate("Imageur3D", u"Scan", None))
        self.label.setText(QCoreApplication.translate("Imageur3D", u"Console :", None))
        self.simulateObjectButton.setText(QCoreApplication.translate("Imageur3D", u"Simuler un objet", None))
        self.label_3.setText(QCoreApplication.translate("Imageur3D", u"Progress :", None))
        self.affichage.setText(QCoreApplication.translate("Imageur3D", u"<html><head/><body><p align=\"center\">Ici s'affichera le r\u00e9sultat des diff\u00e9rentes \u00e9tapes de la simulation</p></body></html>", None))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.result), QCoreApplication.translate("Imageur3D", u"Resultat de la simulation", None))
        self.autoScrollButton.setText(QCoreApplication.translate("Imageur3D", u"AUTO SCROLL", None))
        self.label_2.setText(QCoreApplication.translate("Imageur3D", u"<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Informations</span></p></body></html>", None))
        self.frangesButton.setText(QCoreApplication.translate("Imageur3D", u"G\u00e9n\u00e9rer les franges", None))
        self.TroisDButton.setText(QCoreApplication.translate("Imageur3D", u"Retrouver les \n"
" coordonn\u00e9es 3D", None))
        self.checkBox.setText(QCoreApplication.translate("Imageur3D", u"Bruit", None))
        self.checkBox_2.setText(QCoreApplication.translate("Imageur3D", u"Halo de lumi\u00e8re", None))
        self.autoButton.setText(QCoreApplication.translate("Imageur3D", u"Auto", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.simulationTab), QCoreApplication.translate("Imageur3D", u"Simulation", None))
    # retranslateUi

