# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'test.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QLabel, QListView,
    QMainWindow, QProgressBar, QPushButton, QSizePolicy,
    QTabWidget, QTextBrowser, QWidget)

class Ui_Imageur3D(object):
    def setupUi(self, Imageur3D):
        if not Imageur3D.objectName():
            Imageur3D.setObjectName(u"Imageur3D")
        Imageur3D.resize(1920, 1080)
        Imageur3D.setMinimumSize(QSize(1920, 1080))
        Imageur3D.setMaximumSize(QSize(1920, 1080))
        self.centralwidget = QWidget(Imageur3D)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(9, 9, 1961, 1081))
        self.scanTab = QWidget()
        self.scanTab.setObjectName(u"scanTab")
        self.TroisDButton_3 = QPushButton(self.scanTab)
        self.TroisDButton_3.setObjectName(u"TroisDButton_3")
        self.TroisDButton_3.setGeometry(QRect(430, 780, 141, 51))
        self.label_8 = QLabel(self.scanTab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(1470, 70, 271, 20))
        self.resultTabWidget_3 = QTabWidget(self.scanTab)
        self.resultTabWidget_3.setObjectName(u"resultTabWidget_3")
        self.resultTabWidget_3.setEnabled(True)
        self.resultTabWidget_3.setGeometry(QRect(30, 30, 1280, 746))
        self.result_3 = QWidget()
        self.result_3.setObjectName(u"result_3")
        self.result_3.setStyleSheet(u"background-color : rgb(197,197,197);")
        self.affichage_3 = QLabel(self.result_3)
        self.affichage_3.setObjectName(u"affichage_3")
        self.affichage_3.setGeometry(QRect(0, 0, 1280, 720))
        self.affichage_3.setStyleSheet(u"background-color: rgb(197,197,197);")
        self.resultTabWidget_3.addTab(self.result_3, "")
        self.informationList_3 = QListView(self.scanTab)
        self.informationList_3.setObjectName(u"informationList_3")
        self.informationList_3.setGeometry(QRect(1460, 100, 291, 321))
        self.calibEmetteurButton = QPushButton(self.scanTab)
        self.calibEmetteurButton.setObjectName(u"calibEmetteurButton")
        self.calibEmetteurButton.setGeometry(QRect(40, 810, 113, 41))
        self.calibReceptButton = QPushButton(self.scanTab)
        self.calibReceptButton.setObjectName(u"calibReceptButton")
        self.calibReceptButton.setGeometry(QRect(210, 810, 113, 41))
        self.mire_emet_check = QCheckBox(self.scanTab)
        self.mire_emet_check.setObjectName(u"mire_emet_check")
        self.mire_emet_check.setGeometry(QRect(40, 780, 101, 20))
        self.mire_recep_check = QCheckBox(self.scanTab)
        self.mire_recep_check.setObjectName(u"mire_recep_check")
        self.mire_recep_check.setGeometry(QRect(150, 780, 121, 20))
        self.tabWidget.addTab(self.scanTab, "")
        self.simulationTab = QWidget()
        self.simulationTab.setObjectName(u"simulationTab")
        self.simulateObjectButton = QPushButton(self.simulationTab)
        self.simulateObjectButton.setObjectName(u"simulateObjectButton")
        self.simulateObjectButton.setGeometry(QRect(40, 790, 141, 51))
        self.resultTabWidget = QTabWidget(self.simulationTab)
        self.resultTabWidget.setObjectName(u"resultTabWidget")
        self.resultTabWidget.setGeometry(QRect(30, 30, 1280, 746))
        self.result = QWidget()
        self.result.setObjectName(u"result")
        self.result.setStyleSheet(u"background-color : rgb(197,197,197);")
        self.affichage = QLabel(self.result)
        self.affichage.setObjectName(u"affichage")
        self.affichage.setGeometry(QRect(0, 0, 1280, 720))
        self.affichage.setStyleSheet(u"background-color: rgb(197,255,197);")
        self.resultTabWidget.addTab(self.result, "")
        self.informationList = QListView(self.simulationTab)
        self.informationList.setObjectName(u"informationList")
        self.informationList.setGeometry(QRect(1510, 100, 291, 321))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.informationList.sizePolicy().hasHeightForWidth())
        self.informationList.setSizePolicy(sizePolicy)
        self.label_2 = QLabel(self.simulationTab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(1520, 70, 271, 20))
        self.frangesButton = QPushButton(self.simulationTab)
        self.frangesButton.setObjectName(u"frangesButton")
        self.frangesButton.setGeometry(QRect(190, 810, 201, 31))
        self.TroisDButton = QPushButton(self.simulationTab)
        self.TroisDButton.setObjectName(u"TroisDButton")
        self.TroisDButton.setGeometry(QRect(390, 790, 141, 51))
        self.checkBox = QCheckBox(self.simulationTab)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(190, 790, 51, 20))
        self.checkBox_2 = QCheckBox(self.simulationTab)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(260, 790, 121, 20))
        self.autoButton = QPushButton(self.simulationTab)
        self.autoButton.setObjectName(u"autoButton")
        self.autoButton.setGeometry(QRect(540, 790, 121, 51))
        self.tabWidget.addTab(self.simulationTab, "")
        self.consoleLayout = QTextBrowser(self.centralwidget)
        self.consoleLayout.setObjectName(u"consoleLayout")
        self.consoleLayout.setGeometry(QRect(40, 930, 1051, 131))
        sizePolicy.setHeightForWidth(self.consoleLayout.sizePolicy().hasHeightForWidth())
        self.consoleLayout.setSizePolicy(sizePolicy)
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(780, 890, 301, 23))
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setValue(0)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(640, 880, 191, 41))
        self.label_7.setStyleSheet(u"font: 22pt \"MS Shell Dlg 2\";")
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(50, 890, 111, 31))
        self.label_9.setStyleSheet(u"font: 22pt \"MS Shell Dlg 2\";")
        self.autoScrollButton = QCheckBox(self.centralwidget)
        self.autoScrollButton.setObjectName(u"autoScrollButton")
        self.autoScrollButton.setGeometry(QRect(190, 890, 151, 31))
        sizePolicy.setHeightForWidth(self.autoScrollButton.sizePolicy().hasHeightForWidth())
        self.autoScrollButton.setSizePolicy(sizePolicy)
        self.autoScrollButton.setChecked(True)
        Imageur3D.setCentralWidget(self.centralwidget)

        self.retranslateUi(Imageur3D)

        self.tabWidget.setCurrentIndex(1)
        self.resultTabWidget_3.setCurrentIndex(0)
        self.resultTabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Imageur3D)
    # setupUi

    def retranslateUi(self, Imageur3D):
        Imageur3D.setWindowTitle(QCoreApplication.translate("Imageur3D", u"Imageur 3D", None))
        self.TroisDButton_3.setText(QCoreApplication.translate("Imageur3D", u"Retrouver les \n"
" coordonn\u00e9es 3D", None))
        self.label_8.setText(QCoreApplication.translate("Imageur3D", u"<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Informations</span></p></body></html>", None))
        self.affichage_3.setText(QCoreApplication.translate("Imageur3D", u"<html><head/><body><p align=\"center\">Ici s'affichera le r\u00e9sultat des diff\u00e9rentes \u00e9tapes du scan</p></body></html>", None))
        self.resultTabWidget_3.setTabText(self.resultTabWidget_3.indexOf(self.result_3), QCoreApplication.translate("Imageur3D", u"Resultat du scan", None))
        self.calibEmetteurButton.setText(QCoreApplication.translate("Imageur3D", u"Calibrer \n"
" l'\u00e9metteur", None))
        self.calibReceptButton.setText(QCoreApplication.translate("Imageur3D", u"Calibrer le \n"
" r\u00e9cepteur", None))
        self.mire_emet_check.setText(QCoreApplication.translate("Imageur3D", u"Mire emetteur", None))
        self.mire_recep_check.setText(QCoreApplication.translate("Imageur3D", u"Mire recepteur", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scanTab), QCoreApplication.translate("Imageur3D", u"Scan", None))
        self.simulateObjectButton.setText(QCoreApplication.translate("Imageur3D", u"Simuler un objet", None))
        self.affichage.setText(QCoreApplication.translate("Imageur3D", u"<html><head/><body><p align=\"center\">Ici s'affichera le r\u00e9sultat des diff\u00e9rentes \u00e9tapes de la simulation</p></body></html>", None))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.result), QCoreApplication.translate("Imageur3D", u"Resultat de la simulation", None))
        self.label_2.setText(QCoreApplication.translate("Imageur3D", u"<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Informations</span></p></body></html>", None))
        self.frangesButton.setText(QCoreApplication.translate("Imageur3D", u"G\u00e9n\u00e9rer les franges", None))
        self.TroisDButton.setText(QCoreApplication.translate("Imageur3D", u"Retrouver les \n"
" coordonn\u00e9es 3D", None))
        self.checkBox.setText(QCoreApplication.translate("Imageur3D", u"Bruit", None))
        self.checkBox_2.setText(QCoreApplication.translate("Imageur3D", u"Halo de lumi\u00e8re", None))
        self.autoButton.setText(QCoreApplication.translate("Imageur3D", u"Auto", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.simulationTab), QCoreApplication.translate("Imageur3D", u"Simulation", None))
        self.label_7.setText(QCoreApplication.translate("Imageur3D", u"Progress :", None))
        self.label_9.setText(QCoreApplication.translate("Imageur3D", u"Console :", None))
        self.autoScrollButton.setText(QCoreApplication.translate("Imageur3D", u"AUTO SCROLL", None))
    # retranslateUi

