# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'test.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QLabel, QListView,
    QMainWindow, QProgressBar, QPushButton, QSizePolicy,
    QSlider, QSpinBox, QTabWidget, QTextBrowser,
    QWidget)

class Ui_Imageur3D(object):
    def setupUi(self, Imageur3D):
        if not Imageur3D.objectName():
            Imageur3D.setObjectName(u"Imageur3D")
        Imageur3D.resize(1920, 1080)
        Imageur3D.setMinimumSize(QSize(1920, 1080))
        Imageur3D.setMaximumSize(QSize(1920, 1080))
        self.centralwidget = QWidget(Imageur3D)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1920, 1080))
        self.scanTab = QWidget()
        self.scanTab.setObjectName(u"scanTab")
        self.TroisDButton_3 = QPushButton(self.scanTab)
        self.TroisDButton_3.setObjectName(u"TroisDButton_3")
        self.TroisDButton_3.setGeometry(QRect(610, 800, 141, 51))
        self.label_8 = QLabel(self.scanTab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(1330, 330, 571, 20))
        self.resultTabWidget_3 = QTabWidget(self.scanTab)
        self.resultTabWidget_3.setObjectName(u"resultTabWidget_3")
        self.resultTabWidget_3.setEnabled(True)
        self.resultTabWidget_3.setGeometry(QRect(30, 30, 1280, 746))
        self.result_3 = QWidget()
        self.result_3.setObjectName(u"result_3")
        self.result_3.setStyleSheet(u"background-color : rgb(197,197,197);")
        self.affichage_3 = QLabel(self.result_3)
        self.affichage_3.setObjectName(u"affichage_3")
        self.affichage_3.setGeometry(QRect(0, 0, 1280, 720))
        self.affichage_3.setStyleSheet(u"background-color: rgb(197,197,197);")
        self.resultTabWidget_3.addTab(self.result_3, "")
        self.informationList_3 = QListView(self.scanTab)
        self.informationList_3.setObjectName(u"informationList_3")
        self.informationList_3.setGeometry(QRect(1330, 320, 571, 251))
        self.mire_emet_check = QCheckBox(self.scanTab)
        self.mire_emet_check.setObjectName(u"mire_emet_check")
        self.mire_emet_check.setGeometry(QRect(1460, 360, 101, 20))
        self.mire_recep_check = QCheckBox(self.scanTab)
        self.mire_recep_check.setObjectName(u"mire_recep_check")
        self.mire_recep_check.setGeometry(QRect(1660, 360, 121, 20))
        self.label_cont = QLabel(self.scanTab)
        self.label_cont.setObjectName(u"label_cont")
        self.label_cont.setGeometry(QRect(1606, 100, 61, 21))
        self.label_sat = QLabel(self.scanTab)
        self.label_sat.setObjectName(u"label_sat")
        self.label_sat.setGeometry(QRect(1606, 140, 61, 21))
        self.label_exp = QLabel(self.scanTab)
        self.label_exp.setObjectName(u"label_exp")
        self.label_exp.setGeometry(QRect(1606, 60, 61, 21))
        self.slider_exp = QSlider(self.scanTab)
        self.slider_exp.setObjectName(u"slider_exp")
        self.slider_exp.setGeometry(QRect(1680, 60, 160, 22))
        font = QFont()
        font.setStrikeOut(False)
        self.slider_exp.setFont(font)
        self.slider_exp.setMouseTracking(False)
        self.slider_exp.setMinimum(-10)
        self.slider_exp.setMaximum(10)
        self.slider_exp.setOrientation(Qt.Horizontal)
        self.slider_sat = QSlider(self.scanTab)
        self.slider_sat.setObjectName(u"slider_sat")
        self.slider_sat.setGeometry(QRect(1680, 140, 160, 22))
        self.slider_sat.setMinimum(0)
        self.slider_sat.setMaximum(100)
        self.slider_sat.setValue(100)
        self.slider_sat.setOrientation(Qt.Horizontal)
        self.label_val_exp = QLabel(self.scanTab)
        self.label_val_exp.setObjectName(u"label_val_exp")
        self.label_val_exp.setGeometry(QRect(1850, 60, 41, 21))
        self.slider_cont = QSlider(self.scanTab)
        self.slider_cont.setObjectName(u"slider_cont")
        self.slider_cont.setGeometry(QRect(1680, 100, 160, 22))
        self.slider_cont.setMinimum(0)
        self.slider_cont.setMaximum(100)
        self.slider_cont.setValue(100)
        self.slider_cont.setOrientation(Qt.Horizontal)
        self.label_val_sat = QLabel(self.scanTab)
        self.label_val_sat.setObjectName(u"label_val_sat")
        self.label_val_sat.setGeometry(QRect(1850, 140, 41, 21))
        self.label_val_cont = QLabel(self.scanTab)
        self.label_val_cont.setObjectName(u"label_val_cont")
        self.label_val_cont.setGeometry(QRect(1850, 100, 41, 21))
        self.label_zoom = QLabel(self.scanTab)
        self.label_zoom.setObjectName(u"label_zoom")
        self.label_zoom.setGeometry(QRect(1330, 53, 250, 250))
        self.label_zoom.setStyleSheet(u"background-color: rgb(188, 188, 188);")
        self.number_of_franges = QSpinBox(self.scanTab)
        self.number_of_franges.setObjectName(u"number_of_franges")
        self.number_of_franges.setGeometry(QRect(320, 780, 42, 22))
        self.number_of_franges.setMaximum(10)
        self.number_of_franges.setValue(5)
        self.label = QLabel(self.scanTab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(300, 780, 16, 16))
        self.take_picutres_button = QPushButton(self.scanTab)
        self.take_picutres_button.setObjectName(u"take_picutres_button")
        self.take_picutres_button.setGeometry(QRect(410, 810, 113, 41))
        self.generate_frange_button = QPushButton(self.scanTab)
        self.generate_frange_button.setObjectName(u"generate_frange_button")
        self.generate_frange_button.setGeometry(QRect(280, 810, 113, 31))
        self.afficher_frange_checkbox = QCheckBox(self.scanTab)
        self.afficher_frange_checkbox.setObjectName(u"afficher_frange_checkbox")
        self.afficher_frange_checkbox.setGeometry(QRect(290, 840, 101, 20))
        self.emet_zN_photo_button = QPushButton(self.scanTab)
        self.emet_zN_photo_button.setObjectName(u"emet_zN_photo_button")
        self.emet_zN_photo_button.setGeometry(QRect(1530, 510, 75, 23))
        self.label_3 = QLabel(self.scanTab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(1340, 420, 61, 16))
        self.emet_z0_photo_button = QPushButton(self.scanTab)
        self.emet_z0_photo_button.setObjectName(u"emet_z0_photo_button")
        self.emet_z0_photo_button.setGeometry(QRect(1530, 480, 75, 23))
        self.label_4 = QLabel(self.scanTab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(1410, 480, 71, 21))
        self.label_5 = QLabel(self.scanTab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(1410, 510, 71, 21))
        self.jg = QSpinBox(self.scanTab)
        self.jg.setObjectName(u"jg")
        self.jg.setGeometry(QRect(1430, 510, 42, 22))
        self.jg.setMaximum(1000)
        self.jg.setValue(100)
        self.emet_z0_nb_point_label = QLabel(self.scanTab)
        self.emet_z0_nb_point_label.setObjectName(u"emet_z0_nb_point_label")
        self.emet_z0_nb_point_label.setGeometry(QRect(1610, 480, 101, 21))
        self.emet_zN_nb_point_label = QLabel(self.scanTab)
        self.emet_zN_nb_point_label.setObjectName(u"emet_zN_nb_point_label")
        self.emet_zN_nb_point_label.setGeometry(QRect(1610, 510, 101, 21))
        self.emet_z0_reset_button = QPushButton(self.scanTab)
        self.emet_z0_reset_button.setObjectName(u"emet_z0_reset_button")
        self.emet_z0_reset_button.setGeometry(QRect(1790, 480, 75, 23))
        self.emet_zN_reset_button = QPushButton(self.scanTab)
        self.emet_zN_reset_button.setObjectName(u"emet_zN_reset_button")
        self.emet_zN_reset_button.setGeometry(QRect(1790, 510, 75, 23))
        self.emet_zN_controlz_button = QPushButton(self.scanTab)
        self.emet_zN_controlz_button.setObjectName(u"emet_zN_controlz_button")
        self.emet_zN_controlz_button.setGeometry(QRect(1710, 510, 75, 23))
        self.emet_z0_controlz_button = QPushButton(self.scanTab)
        self.emet_z0_controlz_button.setObjectName(u"emet_z0_controlz_button")
        self.emet_z0_controlz_button.setGeometry(QRect(1710, 480, 75, 23))
        self.z_recep_spinbox = QSpinBox(self.scanTab)
        self.z_recep_spinbox.setObjectName(u"z_recep_spinbox")
        self.z_recep_spinbox.setGeometry(QRect(1430, 430, 42, 22))
        self.z_recep_spinbox.setMaximum(1000)
        self.z_recep_spinbox.setValue(100)
        self.recep_z0_photo_button = QPushButton(self.scanTab)
        self.recep_z0_photo_button.setObjectName(u"recep_z0_photo_button")
        self.recep_z0_photo_button.setGeometry(QRect(1530, 400, 75, 23))
        self.label_6 = QLabel(self.scanTab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(1410, 400, 71, 21))
        self.recep_zN_nb_point_label = QLabel(self.scanTab)
        self.recep_zN_nb_point_label.setObjectName(u"recep_zN_nb_point_label")
        self.recep_zN_nb_point_label.setGeometry(QRect(1610, 430, 101, 21))
        self.recep_z0_nb_point_label = QLabel(self.scanTab)
        self.recep_z0_nb_point_label.setObjectName(u"recep_z0_nb_point_label")
        self.recep_z0_nb_point_label.setGeometry(QRect(1610, 400, 101, 21))
        self.recep_zN_reset_button = QPushButton(self.scanTab)
        self.recep_zN_reset_button.setObjectName(u"recep_zN_reset_button")
        self.recep_zN_reset_button.setGeometry(QRect(1790, 430, 75, 23))
        self.recep_z0_controlz_button = QPushButton(self.scanTab)
        self.recep_z0_controlz_button.setObjectName(u"recep_z0_controlz_button")
        self.recep_z0_controlz_button.setGeometry(QRect(1710, 400, 75, 23))
        self.label_10 = QLabel(self.scanTab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(1410, 430, 16, 21))
        self.recep_zN_controlz_button = QPushButton(self.scanTab)
        self.recep_zN_controlz_button.setObjectName(u"recep_zN_controlz_button")
        self.recep_zN_controlz_button.setGeometry(QRect(1710, 430, 75, 23))
        self.recep_z0_reset_button = QPushButton(self.scanTab)
        self.recep_z0_reset_button.setObjectName(u"recep_z0_reset_button")
        self.recep_z0_reset_button.setGeometry(QRect(1790, 400, 75, 23))
        self.label_11 = QLabel(self.scanTab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(1340, 500, 61, 16))
        self.recep_zN_photo_button = QPushButton(self.scanTab)
        self.recep_zN_photo_button.setObjectName(u"recep_zN_photo_button")
        self.recep_zN_photo_button.setGeometry(QRect(1530, 430, 75, 23))
        self.tabWidget.addTab(self.scanTab, "")
        self.TroisDButton_3.raise_()
        self.resultTabWidget_3.raise_()
        self.informationList_3.raise_()
        self.mire_emet_check.raise_()
        self.mire_recep_check.raise_()
        self.label_cont.raise_()
        self.label_sat.raise_()
        self.label_exp.raise_()
        self.slider_exp.raise_()
        self.slider_sat.raise_()
        self.label_val_exp.raise_()
        self.slider_cont.raise_()
        self.label_val_sat.raise_()
        self.label_val_cont.raise_()
        self.label_zoom.raise_()
        self.number_of_franges.raise_()
        self.label.raise_()
        self.take_picutres_button.raise_()
        self.generate_frange_button.raise_()
        self.afficher_frange_checkbox.raise_()
        self.label_8.raise_()
        self.emet_zN_photo_button.raise_()
        self.label_3.raise_()
        self.emet_z0_photo_button.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.jg.raise_()
        self.emet_z0_nb_point_label.raise_()
        self.emet_zN_nb_point_label.raise_()
        self.emet_z0_reset_button.raise_()
        self.emet_zN_reset_button.raise_()
        self.emet_zN_controlz_button.raise_()
        self.emet_z0_controlz_button.raise_()
        self.z_recep_spinbox.raise_()
        self.recep_z0_photo_button.raise_()
        self.label_6.raise_()
        self.recep_zN_nb_point_label.raise_()
        self.recep_z0_nb_point_label.raise_()
        self.recep_zN_reset_button.raise_()
        self.recep_z0_controlz_button.raise_()
        self.label_10.raise_()
        self.recep_zN_controlz_button.raise_()
        self.recep_z0_reset_button.raise_()
        self.label_11.raise_()
        self.recep_zN_photo_button.raise_()
        self.simulationTab = QWidget()
        self.simulationTab.setObjectName(u"simulationTab")
        self.simulateObjectButton = QPushButton(self.simulationTab)
        self.simulateObjectButton.setObjectName(u"simulateObjectButton")
        self.simulateObjectButton.setGeometry(QRect(40, 790, 141, 51))
        self.resultTabWidget = QTabWidget(self.simulationTab)
        self.resultTabWidget.setObjectName(u"resultTabWidget")
        self.resultTabWidget.setGeometry(QRect(30, 30, 1280, 746))
        self.resultTabWidget.setStyleSheet(u"")
        self.result = QWidget()
        self.result.setObjectName(u"result")
        self.result.setStyleSheet(u"background-color : rgb(197,197,197);")
        self.affichage = QLabel(self.result)
        self.affichage.setObjectName(u"affichage")
        self.affichage.setGeometry(QRect(0, 0, 1280, 720))
        self.affichage.setStyleSheet(u"background-color: rgb(197,255,197);")
        self.resultTabWidget.addTab(self.result, "")
        self.informationList = QListView(self.simulationTab)
        self.informationList.setObjectName(u"informationList")
        self.informationList.setGeometry(QRect(1510, 100, 291, 321))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.informationList.sizePolicy().hasHeightForWidth())
        self.informationList.setSizePolicy(sizePolicy)
        self.label_2 = QLabel(self.simulationTab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(1520, 70, 271, 20))
        self.frangesButton = QPushButton(self.simulationTab)
        self.frangesButton.setObjectName(u"frangesButton")
        self.frangesButton.setGeometry(QRect(190, 810, 201, 31))
        self.TroisDButton = QPushButton(self.simulationTab)
        self.TroisDButton.setObjectName(u"TroisDButton")
        self.TroisDButton.setGeometry(QRect(390, 790, 141, 51))
        self.checkBox = QCheckBox(self.simulationTab)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(190, 790, 51, 20))
        self.checkBox_2 = QCheckBox(self.simulationTab)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(260, 790, 121, 20))
        self.autoButton = QPushButton(self.simulationTab)
        self.autoButton.setObjectName(u"autoButton")
        self.autoButton.setGeometry(QRect(540, 790, 121, 51))
        self.tabWidget.addTab(self.simulationTab, "")
        self.consoleLayout = QTextBrowser(self.centralwidget)
        self.consoleLayout.setObjectName(u"consoleLayout")
        self.consoleLayout.setGeometry(QRect(40, 930, 1271, 131))
        sizePolicy.setHeightForWidth(self.consoleLayout.sizePolicy().hasHeightForWidth())
        self.consoleLayout.setSizePolicy(sizePolicy)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(50, 890, 111, 31))
        self.label_9.setStyleSheet(u"font: 22pt \"MS Shell Dlg 2\";")
        self.autoScrollButton = QCheckBox(self.centralwidget)
        self.autoScrollButton.setObjectName(u"autoScrollButton")
        self.autoScrollButton.setGeometry(QRect(190, 890, 151, 31))
        sizePolicy.setHeightForWidth(self.autoScrollButton.sizePolicy().hasHeightForWidth())
        self.autoScrollButton.setSizePolicy(sizePolicy)
        self.autoScrollButton.setChecked(True)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(864, 886, 191, 41))
        self.label_7.setStyleSheet(u"font: 22pt \"MS Shell Dlg 2\";")
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(1000, 900, 301, 23))
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setValue(0)
        self.save_img_button = QPushButton(self.centralwidget)
        self.save_img_button.setObjectName(u"save_img_button")
        self.save_img_button.setGeometry(QRect(1160, 800, 151, 41))
        Imageur3D.setCentralWidget(self.centralwidget)

        self.retranslateUi(Imageur3D)

        self.tabWidget.setCurrentIndex(0)
        self.resultTabWidget_3.setCurrentIndex(0)
        self.resultTabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Imageur3D)
    # setupUi

    def retranslateUi(self, Imageur3D):
        Imageur3D.setWindowTitle(QCoreApplication.translate("Imageur3D", u"Imageur 3D", None))
        self.TroisDButton_3.setText(QCoreApplication.translate("Imageur3D", u"Retrouver les \n"
" coordonn\u00e9es 3D", None))
        self.label_8.setText(QCoreApplication.translate("Imageur3D", u"<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Calibration</span></p><p align=\"center\"><br/></p></body></html>", None))
        self.affichage_3.setText(QCoreApplication.translate("Imageur3D", u"<html><head/><body><p align=\"center\">Ici s'affichera le r\u00e9sultat des diff\u00e9rentes \u00e9tapes du scan</p></body></html>", None))
        self.resultTabWidget_3.setTabText(self.resultTabWidget_3.indexOf(self.result_3), QCoreApplication.translate("Imageur3D", u"Resultat du scan", None))
        self.mire_emet_check.setText(QCoreApplication.translate("Imageur3D", u"Mire emetteur", None))
        self.mire_recep_check.setText(QCoreApplication.translate("Imageur3D", u"Mire recepteur", None))
        self.label_cont.setText(QCoreApplication.translate("Imageur3D", u"Contraste", None))
        self.label_sat.setText(QCoreApplication.translate("Imageur3D", u"Saturation", None))
        self.label_exp.setText(QCoreApplication.translate("Imageur3D", u"Exposition", None))
        self.label_val_exp.setText(QCoreApplication.translate("Imageur3D", u"0", None))
        self.label_val_sat.setText(QCoreApplication.translate("Imageur3D", u"100", None))
        self.label_val_cont.setText(QCoreApplication.translate("Imageur3D", u"100", None))
        self.label_zoom.setText("")
        self.label.setText(QCoreApplication.translate("Imageur3D", u"N:", None))
        self.take_picutres_button.setText(QCoreApplication.translate("Imageur3D", u"Prendre les \n"
" photos", None))
        self.generate_frange_button.setText(QCoreApplication.translate("Imageur3D", u"g\u00e9nerer franges", None))
        self.afficher_frange_checkbox.setText(QCoreApplication.translate("Imageur3D", u"Afficher franges", None))
        self.emet_zN_photo_button.setText(QCoreApplication.translate("Imageur3D", u"PHOTO", None))
        self.label_3.setText(QCoreApplication.translate("Imageur3D", u"RECEPTEUR", None))
        self.emet_z0_photo_button.setText(QCoreApplication.translate("Imageur3D", u"PHOTO", None))
        self.label_4.setText(QCoreApplication.translate("Imageur3D", u"Z=0", None))
        self.label_5.setText(QCoreApplication.translate("Imageur3D", u"Z=", None))
        self.emet_z0_nb_point_label.setText(QCoreApplication.translate("Imageur3D", u"0/9 POINTS", None))
        self.emet_zN_nb_point_label.setText(QCoreApplication.translate("Imageur3D", u"0/9 POINTS", None))
        self.emet_z0_reset_button.setText(QCoreApplication.translate("Imageur3D", u"RESET", None))
        self.emet_zN_reset_button.setText(QCoreApplication.translate("Imageur3D", u"RESET", None))
        self.emet_zN_controlz_button.setText(QCoreApplication.translate("Imageur3D", u"control Z", None))
        self.emet_z0_controlz_button.setText(QCoreApplication.translate("Imageur3D", u"control Z", None))
        self.recep_z0_photo_button.setText(QCoreApplication.translate("Imageur3D", u"PHOTO", None))
        self.label_6.setText(QCoreApplication.translate("Imageur3D", u"Z=0", None))
        self.recep_zN_nb_point_label.setText(QCoreApplication.translate("Imageur3D", u"0/9 POINTS", None))
        self.recep_z0_nb_point_label.setText(QCoreApplication.translate("Imageur3D", u"0/9 POINTS", None))
        self.recep_zN_reset_button.setText(QCoreApplication.translate("Imageur3D", u"RESET", None))
        self.recep_z0_controlz_button.setText(QCoreApplication.translate("Imageur3D", u"control Z", None))
        self.label_10.setText(QCoreApplication.translate("Imageur3D", u"Z=", None))
        self.recep_zN_controlz_button.setText(QCoreApplication.translate("Imageur3D", u"control Z", None))
        self.recep_z0_reset_button.setText(QCoreApplication.translate("Imageur3D", u"RESET", None))
        self.label_11.setText(QCoreApplication.translate("Imageur3D", u"EMETEUR", None))
        self.recep_zN_photo_button.setText(QCoreApplication.translate("Imageur3D", u"PHOTO", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scanTab), QCoreApplication.translate("Imageur3D", u"Scan", None))
        self.simulateObjectButton.setText(QCoreApplication.translate("Imageur3D", u"Simuler un objet", None))
        self.affichage.setText(QCoreApplication.translate("Imageur3D", u"<html><head/><body><p align=\"center\">Ici s'affichera le r\u00e9sultat des diff\u00e9rentes \u00e9tapes de la simulation</p></body></html>", None))
        self.resultTabWidget.setTabText(self.resultTabWidget.indexOf(self.result), QCoreApplication.translate("Imageur3D", u"Resultat de la simulation", None))
        self.label_2.setText(QCoreApplication.translate("Imageur3D", u"<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Informations</span></p></body></html>", None))
        self.frangesButton.setText(QCoreApplication.translate("Imageur3D", u"G\u00e9n\u00e9rer les franges", None))
        self.TroisDButton.setText(QCoreApplication.translate("Imageur3D", u"Retrouver les \n"
" coordonn\u00e9es 3D", None))
        self.checkBox.setText(QCoreApplication.translate("Imageur3D", u"Bruit", None))
        self.checkBox_2.setText(QCoreApplication.translate("Imageur3D", u"Halo de lumi\u00e8re", None))
        self.autoButton.setText(QCoreApplication.translate("Imageur3D", u"Auto", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.simulationTab), QCoreApplication.translate("Imageur3D", u"Simulation", None))
        self.label_9.setText(QCoreApplication.translate("Imageur3D", u"Console :", None))
        self.autoScrollButton.setText(QCoreApplication.translate("Imageur3D", u"AUTO SCROLL", None))
        self.label_7.setText(QCoreApplication.translate("Imageur3D", u"Progress :", None))
        self.save_img_button.setText(QCoreApplication.translate("Imageur3D", u"Sauvegarder image", None))
    # retranslateUi

